-- Drop Tables

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS shops CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS shop_owners CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- Drop Views

DROP VIEW IF EXISTS user_role_view;
DROP VIEW IF EXISTS admin_users;
DROP VIEW IF EXISTS user_orders_view;


-- Drop Procedures
DROP PROCEDURE IF EXISTS add_new_user(VARCHAR,VARCHAR,TEXT,INTEGER);
DROP PROCEDURE IF EXISTS add_new_order(INTEGER, INTEGER, JSON);