-- Drop Tables

DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS shop CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS custom_order CASCADE;
DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS shop_owner CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;

-- Drop Views

DROP VIEW IF EXISTS user_role_view;
DROP VIEW IF EXISTS admin_user_view;
DROP VIEW IF EXISTS user_order_view;


-- Drop Procedures
DROP PROCEDURE IF EXISTS add_new_user(VARCHAR,VARCHAR,TEXT,INTEGER);
DROP PROCEDURE IF EXISTS add_new_order(INTEGER, INTEGER, JSON);